In [ ]:
# https://www.kaggle.com/general/274656
try:
    import tensorflow as tf
    import pandas as pd
except:
    %pip install pandas
    %pip install tensorflow
    %pip install --ignore-installed --upgrade tensorflow-gpu==1.15.0
    import tensorflow as tf

### Printing

In Python, we ask a computer to print a message for us by writing `print()` and putting the message inside the parentheses and enclosed in quotation marks. 

In [2]:
print("Hello, Python")

Hello, Python


### Arithmetic

In Python, we can do arithmetic by writing the operation and the numbers we want to use. For example, we can add two numbers together by writing `+` and the numbers we want to add.

In [3]:
print("1 + 2: ", 1 + 2)

print("9 - 2: ", 9 - 2)

print("3 * 2: ", 3 * 2)

print("3 / 2: ", 3 / 2)

print("3 // 2: ", 3 // 2)

print("3 ** 2: ", 3 ** 2)

print("3 % 2: ", 3 % 2)

print("3 + 2 * 2: ", 3 + 2 * 2)

print("((1 + 3) * (9 - 2) / 2) ** 2: ", ((1 + 3) * (9 - 2) / 2) ** 2)

1 + 2:  3
9 - 2:  7
3 * 2:  6
3 / 2:  1.5
3 // 2:  1
3 ** 2:  9
3 % 2:  1
3 + 2 * 2:  7
((1 + 3) * (9 - 2) / 2) ** 2:  196.0


### Variables

In Python, we can store a value in a variable by writing the variable name and then the value we want to store. For example, we can store the number 5 in a variable called `x` by writing `x = 5`.

Variable names are ideally short and descriptive. They can only include letters, numbers, and underscores (e.g., `test_var!` is not allowed). They have to start with a letter or underscore (e.g., `1_var` is not allowed). They can't have spaces (e.g., `test var` is not allowed). They are case sensitive (e.g., `test_var` and `Test_var` are different variables).

Variable's scope as the part of the code where it is accessible. Variables defined inside a function have a local scope of that function only. Variables defined outside all functions have a global scope and can be accessed anywhere.

In [4]:
# create a variable
ex_var = 1

# print the value of ex_var
print("ex_var: ", ex_var)

ex_var:  1


In [6]:
my_var = 10

print("original my_var: ", my_var)

# manipulate the value of my_var
my_var = 20

print("changed my_var: ", my_var)

original my_var:  10
changed my_var:  20


In [7]:
# increment the value of my_var
my_var += 10

print("incremented my_var: ", my_var)

incremented my_var:  30


In [10]:
# calculate number of seconds in four years

num_years = 4

# 1 year = 365 days
days_per_year = 365

# 1 day = 24 hours
hours_per_day = 24

# 1 hour = 60 minutes
minutes_per_hour = 60

# 1 minute = 60 seconds
seconds_per_minute = 60

# 4 years = 4 * 365 days
num_days = num_years * days_per_year

total_seconds = num_days * hours_per_day * minutes_per_hour * seconds_per_minute
print(total_seconds)

# Note it is possible to do this calculation without variables as just 60 * 60 * 24 * 365 * 4, 
# but it is much harder to check that the calculation without variables does not have some error, 
# because it is not as readable. 
# Use variables  keep track of each part of the calculation and more easily check for and correct any mistakes.

126144000


In [11]:
# average 250 babies born each minute
births_per_min = 250

# average number of babies born each day
births_per_day = births_per_min * 60 * 24

print(births_per_day)

360000


In [17]:
import pandas as pd
titanic_data = pd.read_csv("../data/titanic.csv")

#show the first 5 rows of the titanic dataset
titanic_data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [1]:
print("Number of total passengers on Titanic: ", len(titanic_data))

print("Number of passengers in first class: ", len(titanic_data[titanic_data["Pclass"] == 1]))

print("Number of minor passengers: ", len(titanic_data[titanic_data["Age"] < 18]))

print("Number of passengers who survived: ", (titanic_data.Survived == 1).sum())

# For fraction, divide the number of survivors by the total number of people on board
print("The fraction of passengers who survived the Titanic disaster: ", (titanic_data["Survived"] == 1).mean())

print("The fraction of passengers who were minors: ", (titanic_data["Age"] < 18).mean())

NameError: name 'titanic_data' is not defined

### Functions

In Python, we can define a function by writing `def` and then the function name and the function parameters in parentheses. We then write the function code indented below the function definition. For example, we can define a function called `add` that adds two numbers together.

In [23]:
def add_two_numbers(x, y):
    return x + y

def add_three_numbers(x, y, z):
    return x + y + z

def increment(x):
    return x + 1

def increment_by_10(x):
    return x + 10

# run (or "call") a function
result = add_two_numbers(1, 2)
print(result)

3


In [25]:
# Calculate weekly paycheck after taxes.
# They're in a 12% tax bracket (in other words, 12% of their salary is taken for taxes, 
# and they only take home 88%), and they're paid hourly, at a rate of $15/hour.
# The function below calculates the paycheck based on the number of hours worked.

def calculate_paycheck(hours_worked):
    hourly_rate = 15
    paycheck = hours_worked * hourly_rate
    paycheck_after_taxes = paycheck * (1 - 12/100)
    return paycheck_after_taxes

# Calculate the paycheck for someone who worked 40 hours
print("Paycheck for someone who worked 40 hours: ", calculate_paycheck(40))

# Calculate the paycheck for someone who worked 25 hours
print("Paycheck for someone who worked 25 hours: ", calculate_paycheck(25))

Paycheck for someone who worked 40 hours:  528.0
Paycheck for someone who worked 25 hours:  330.0


In [27]:
def calculate_paycheck(hours_worked, hourly_rate, tax_rate):
    paycheck = hours_worked * hourly_rate
    paycheck_after_taxes = paycheck * (1 - tax_rate/100)
    return paycheck_after_taxes

# Calculate the paycheck for someone who worked 40 hours
print("Paycheck for someone who worked 40 hours: ", calculate_paycheck(40, 15, 12))
print("Paycheck for someone who worked 40 hours: ", calculate_paycheck(40, 24, 22))

Paycheck for someone who worked 40 hours:  528.0
Paycheck for someone who worked 40 hours:  748.8000000000001


In [28]:
house_prices_data = pd.read_csv("../data/house_prices.csv")
house_prices_data.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [33]:
def calculate_mean_price(data):
    return data["SalePrice"].mean()

print("Mean house price: ", calculate_mean_price(house_prices_data))

def calculate_mean_area(data):
    return data["GrLivArea"].mean()

print("Mean house area: ", calculate_mean_area(house_prices_data))


Mean house price:  180921.19589041095
Mean house area:  1515.463698630137


In [34]:
def get_cost(sqft_walls, sqft_ceiling, sqft_per_gallon, cost_per_gallon):
    cost = (sqft_walls + sqft_ceiling) / sqft_per_gallon * cost_per_gallon
    return cost

# Calculate the cost of painting a 10x10 room with 8 foot ceilings
print("Cost of painting a 10x10 room with 8 foot ceilings: ", get_cost(10 * 8 * 4, 10 * 10, 350, 25))

# Calculate the cost of painting: sqft_walls=432, sqft_ceiling=144, sqft_per_gallon=400, cost_per_gallon=15
print("Cost of painting a 12x12 room with 9 foot ceilings: ", get_cost(432, 144, 400, 15))

Cost of painting a 10x10 room with 8 foot ceilings:  30.0
Cost of painting a 12x12 room with 9 foot ceilings:  21.599999999999998


In [39]:
from math import ceil

def get_actual_cost(sqft_walls, sqft_ceiling, sqft_per_gallon, cost_per_gallon):
    gallons = (sqft_walls + sqft_ceiling) / sqft_per_gallon
    gallons_to_buy = ceil(gallons)
    cost = gallons_to_buy * cost_per_gallon
    return cost

print("Cost of painting: ", get_actual_cost(432, 144, 400, 15))
print("Cost of painting: ", get_actual_cost(594, 288, 400, 15))

Cost of painting:  30
Cost of painting:  45


### Data types

In Python, we can store different types of data. The most common data types are strings, integers, floats, and booleans. This is just a small subset of the available data types -- there are also dictionaries, sets, lists, tuples, and much more.

Data types are important, because they determine what kinds of actions you can do with them. For example, you can't add two strings together, but you can add two integers together. You can't add a string and an integer together. Similarly, you can divide two floats, but you cannot divide two strings. To avoid errors, we need to make sure that the actions match the data types that we have.

We can check the type of a variable by using the `type()` function.

In [47]:
from math import pi

x = 15
print("x: ", x)
print("type of x: ", type(x))

pi_val = pi
print("Pi value: ", pi_val)
print("Rounded Pi value: ", round(pi_val, 2))
print("type of Pi: ", type(pi_val))

z = 15 < 20
print("z: ", z)
print("type of z: ", type(z))

not_z = not z
print("not z: ", not_z)
print("type of not z: ", type(not_z))

print("3 * True: ", 3 * True)
print("-3.1 * True", -3.1 * True)
print("Type of \"abc\" * False: ", type("abc" * False))
print("Length of \"abc\" * False", len("abc" * False))

print(False + False)
print(True + False)
print(False + True)
print(True + True)
print(False + True + True + True)

w = "Hello, Python!"
print("w: ", w)
print("type of w: ", type(w))
print("length of w: ", len(w))
print("w + welcome: ", w + " Welcome to the world of Python!")


x:  15
type of x:  <class 'int'>
Pi value:  3.141592653589793
Rounded Pi value:  3.14
type of Pi:  <class 'float'>
z:  True
type of z:  <class 'bool'>
not z:  False
type of not z:  <class 'bool'>
3 * True:  3
-3.1 * True -3.1
Type of "abc" * False:  <class 'str'>
Length of "abc" * False 0
w:  Hello, Python!
type of w:  <class 'str'>
length of w:  14
w + welcome:  Hello, Python! Welcome to the world of Python!


In [48]:
# You offer both gold plated and solid gold rings.
# Gold plated rings have a base cost of $50, and you charge $7 per engraved unit.
# Solid gold rings have a base cost of $100, and you charge $10 per engraved unit.
# Spaces and punctuation are counted as engraved units.

def cost_of_project(engraving, solid_gold):
    if (solid_gold):
        cost = 100 + 10 * len(engraving)
    else:
        cost = 50 + 7 * len(engraving)
    return cost

cost_of_project("Charlie+Denver", True)

cost_of_project("08/10/2000", False)

120

### Conditionals

In programming, conditions are statements that are either `True` or `False`

In [ ]:
var_one = 1
var_two = 2

print(var_one < 1)
print(var_two >= var_one)

In [50]:
# evaluate_temp() function accepts a body temperature (in Celcius) as input
# Initially, message is set to "Normal temperature".
# Then, if temp > 38 is True (e.g., the body temperature is greater than 38°C), the message is updated to "Fever!". Otherwise, if temp > 38 is False, then the message is not updated.
# Finally, message is returned by the function.

def evaluate_temp(temp):
    message = "Normal temperature"
    if temp > 38:
        message = "Fever!"
    return message

print(evaluate_temp(37))
print(evaluate_temp(38.5))

Normal temperature
Fever!


In [ ]:
def evaluate_temp_with_else(temp):
    if temp > 38:
        message = "Fever!"
    else:
        message = "Normal temperature."
    return message

In [ ]:
def evaluate_temp_with_elif(temp):
    if temp > 38:
        message = "Fever!"
    elif temp > 35:
        message = "Normal temperature."
    else:
        message = "Low temperature."
    return message

In [51]:
# You live in a country with only two tax brackets. 
# Everyone earning less than 12,000 pays 25% in taxes, and 
# anyone earning 12,000 or more pays 30%. 
# The function below calculates how much tax is owed

def get_taxes(earnings):
    if earnings < 12000:
        taxes = earnings * 0.25
    else:
        taxes = earnings * 0.30
    return taxes

print(get_taxes(10000))
print(get_taxes(12000))

2500.0
3600.0


In [ ]:
# a function get_grade() takes score as input ranging from 0-100 and 
# returns the corresponding letter grade
# "A" - any grade 90-100, inclusive
# "B" - any grade 80-89, inclusive
# "C" - any grade 70-79, inclusive
# "D" - any grade 60-69, inclusive
# "F" - any grade <60

def get_grades(score):
    if score >= 90:
        grade = "A"
    elif score >= 80:
        grade = "B"
    elif score >= 70:
        grade = "C"
    elif score >= 60:
        grade = "D"
    else:
        grade = "F"
    return grade

In [55]:
# a function get_water_bill() that takes as input:
# num_gallons = the number of gallons of water that a customer used that month. 
# (This will always be an integer with no decimal part.)
# output: the water bill for that customer, in dollars.

# Tier	Amount in gallons	Price per 1000 gallons
# Tier 1	0 - 8,000	$5
# Tier 2	8,001 - 22,000	$6
# Tier 3	22,001 - 30,000	$7
# Tier 4	30,001+	$10

# Someone who uses 10,000 gallons of water in a month is placed in Tier 2, and needs to pay a water bill of $6 * 10 = $60. In other words, get_water_bill(10000) should return 60.0.
# Someone who uses 25,000 gallons of water in a month is placed in Tier 3, and needs to pay a water bill of $7 * 25 = $175. In other words, get_water_bill(25000) should return 175.0.

def get_water_bill(num_gallons):
    if num_gallons <= 8000:
        bill = num_gallons * 0.005
    elif num_gallons <= 22000:
        bill = num_gallons * 0.006
    elif num_gallons <= 30000:
        bill = num_gallons * 0.007
    else:
        bill = num_gallons * 0.01
    return bill

print(get_water_bill(10000))
print(get_water_bill(25000))

60.0
175.0


In [1]:
# You work for a company that provides data services. 
# For $100/month, your company provides 15 gigabytes (GB) of data. 
# Then, any additional data is billed at $0.10/MB (or $100/GB, since 1,000 MB are in 1 GB).

# write a function get_phone_bill() that takes as input:

# gb = number of GB that the customer used in a month
# It should return the customer's total phone bill.

# For instance:

# A customer who uses 10 GB of data in one month is billed only $100, 
# since the usage stayed under 15 GB. In other words, get_phone_bill(10) should return 100.

# A customer who uses 15.1 GB (or 15 GB + 100 MB) of data in one month has gone over by .1 GB, 
# so they must pay $100 (cost of plan), plus $0.10 * 100 = $10, for a total bill of $110. 
# In other words, get_phone_bill(15.1) should return 110.

def get_phone_bill(gb):
    if gb <= 15:
        bill = 100
    else:
        bill = 100 + (gb - 15) * 100
    return bill

print(get_phone_bill(10))

100


### Lists

In Python, we can store multiple values in a list. We can create a list by writing the values inside square brackets and separating them by commas. For example, we can create a list of numbers.

In [4]:
flowers = "pink primrose,hard-leaved pocket orchid,canterbury bells,sweet pea,english marigold,tiger lily,moon orchid,bird of paradise,monkshood,globe thistle"
flowers_list = flowers.split(",")
print("Flowers: ", flowers_list)

# Write a function get_flower() that takes as input a flower name (as a string) and returns the corresponding position in the list.
def get_flower(flower_name):
    return flowers_list.index(flower_name)

print(get_flower("sweet pea"))

Flowers:  ['pink primrose', 'hard-leaved pocket orchid', 'canterbury bells', 'sweet pea', 'english marigold', 'tiger lily', 'moon orchid', 'bird of paradise', 'monkshood', 'globe thistle']
3


In [ ]:
menu = ['stewed meat with onions', 'bean soup', 'risotto with trout and shrimp',
       'fish soup with cream and onion', 'gyro']

# remove bean soup from the menu
menu.remove("bean soup")

# add "chicken soup" to the menu
menu.append("chicken soup")

# replace "gyro" with "chicken gyro"
menu[4] = "chicken gyro"

In [7]:
# The list num_customers contains the number of customers who came into your restaurant every day over the last month (which lasted thirty days). Fill in values for each of the following:

# avg_first_seven - average number of customers who visited in the first seven days
# avg_last_seven - average number of customers who visited in the last seven days
# max_month - number of customers on the day that got the most customers in the last month
# min_month - number of customers on the day that got the least customers in the last month

# If you have to find the minimum value in a list, use min() instead of scanning for the smallest value and directly filling in a number.

# Number of customers each day for the last month
num_customers = [137, 147, 135, 128, 170, 174, 165, 146, 126, 159,
                 141, 148, 132, 147, 168, 153, 170, 161, 148, 152,
                 141, 151, 131, 149, 164, 163, 143, 143, 166, 171]

avg_first_seven = sum(num_customers[:7]) / 7
print("avg_first_seven: ", avg_first_seven)

avg_last_seven = sum(num_customers[-7:]) / 7
print("avg_last_seven: ", avg_last_seven)

max_month = max(num_customers)

min_month = min(num_customers)

150.85714285714286


In [16]:
def percentage_liked(ratings):
    list_liked = [i>=4 for i in ratings]
    print("list_liked: ", list_liked)
    percentage_liked = sum(list_liked) / len(list_liked)
    return percentage_liked

# should return 0.5
percentage_liked([1, 2, 3, 4, 5, 4, 5, 1])

list_liked:  [False, False, False, True, True, True, True, False]


1.0

In [17]:
"""
write a function that returns the percentage growth in the total number of users relative to a specified number of years ago.

Your function percentage_growth() should take two arguments as input:

num_users = Python list with the total number of users each year. So num_users[0] is the total number of users in the first year, num_users[1] is the total number of users in the second year, and so on. The final entry in the list gives the total number of users in the most recently completed year.
yrs_ago = number of years to go back in time when calculating the growth percentage
For instance, say num_users = [920344, 1043553, 1204334, 1458996, 1503323, 1593432, 1623463, 1843064, 1930992, 2001078].

if yrs_ago = 1, we want the function to return a value of about 0.036. This corresponds to a percentage growth of approximately 3.6%, calculated as (2001078 - 1930992)/1930992.
if years_ago = 7, we would want to return approximately 0.66. This corresponds to a percentage growth of approximately 66%, calculated as (2001078 - 1204334)/1204334.
"""

def percentage_growth(num_users, yrs_ago):
    return (num_users[-1] - num_users[-1-yrs_ago]) / num_users[-1-yrs_ago]

num_users_test = [920344, 1043553, 1204334, 1458996, 1503323, 1593432, 1623463, 1843064, 1930992, 2001078]

print(percentage_growth(num_users_test, 1))
print(percentage_growth(num_users_test, 7))

0.03629533421163837
0.6615639847417742


In [18]:
def is_valid_zip(zip_code):
    """Returns whether the input string is a valid (5 digit) zip code
    """
    def hasDigits(pin_code):
        return pin_code.isdigit()
    if (len(zip_code) == 5 and hasDigits(zip_code)):
        return True
    return False

print(is_valid_zip("12345"))

True


In [5]:
doc_list = ["The Learn Python Challenge Casino.", "They bought a car", "Casinoville"]
print("Casinoville" in doc_list)

True


In [20]:
def word_search(doc_list, keyword):
    indices = []
    for i, doc in enumerate(doc_list):
        tokens = doc.split()
        normalized = [token.rstrip('.,').lower() for token in tokens]
        if keyword.lower() in normalized:
            indices.append(i)
    return indices

doc_list = ["The Learn Python Challenge Casino.", "They bought a car and a casino", "Casinoville"]
print(word_search(doc_list, 'casino'))

[0, 1]


In [22]:
def multi_word_search(doc_list, keywords):
    """
    Takes list of documents (each document is a string) and a list of keywords.  
    Returns a dictionary where each key is a keyword, and the value is a list of indices
    (from doc_list) of the documents containing that keyword

    >>> doc_list = ["The Learn Python Challenge Casino.", "They bought a car and a casino", "Casinoville"]
    >>> keywords = ['casino', 'they']
    >>> multi_word_search(doc_list, keywords)
    {'casino': [0, 1], 'they': [1]}
    """
    indices = {}
    for keyword in keywords:
        indices[keyword] = word_search(doc_list, keyword)
    return indices

doc_list = ["The Learn Python Challenge Casino.", "They bought a car and a casino", "Casinoville"]
multi_word_search(doc_list, ['casino', 'they'])

{'casino': [0, 1], 'they': [1]}

### Operator overloading

In Python, we can use the same operator to do different things depending on the data type. For example, we can use the `+` operator to add two numbers together or to concatenate two strings together.

In [27]:
import math

print("It's math! It has type {}".format(type(math)))

print("pi to 4 significant digits = {:.4}".format(math.pi))

math.log(32, 2)

help(math.log)

help(math)

print(dir(math))

It's math! It has type <class 'module'>
pi to 4 significant digits = 3.142
Help on built-in function log in module math:

log(...)
    log(x, [base=math.e])
    Return the logarithm of x to the given base.
    
    If the base not specified, returns the natural logarithm (base e) of x.

Help on module math:

NAME
    math

MODULE REFERENCE
    https://docs.python.org/3.9/library/math
    
    The following documentation is automatically generated from the Python
    source files.  It may be incomplete, incorrect or include features that
    are considered implementation detail and may vary between Python
    implementations.  When in doubt, consult the module reference at the
    location listed above.

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.
        
        The result is between 0 and pi.
    
    acosh(x, /)
        Return the inverse h

In [16]:
import numpy as np

print("It's numpy! It has type {}".format(type(np)))

print("some methods:", dir(np.random)[-5:])

rolls = np.random.randint(low=1, high=6, size=10)
print("dice rolls:", rolls)

print("add 100 to rolls:", rolls + 100)

print("mean of rolls:", np.mean(rolls))

print("type of rolls:", type(rolls))

print("some methods that can be applied on rolls:", dir(rolls)[-5:])

It's numpy! It has type <class 'module'>
some methods: ['uniform', 'vonmises', 'wald', 'weibull', 'zipf']
dice rolls: [2 3 4 4 1 3 1 5 4 1]
add 100 to rolls: [102 103 104 104 101 103 101 105 104 101]
check:  [ True  True  True  True  True  True  True  True  True  True]
mean of rolls: 2.8
type of rolls: <class 'numpy.ndarray'>
some methods that can be applied on rolls: ['tostring', 'trace', 'transpose', 'var', 'view']


In [24]:
# 3 x 3 matrix
matrix_3x3 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print("3 x 3 matrix:", matrix_3x3)

matrix_3x3_np = np.asarray(matrix_3x3)
print("3 x 3 matrix in numpy:", matrix_3x3_np)

print("last row of matrix_3x3_np:", matrix_3x3_np[-1])

print("last element of last row of matrix_3x3_np:", matrix_3x3_np[-1][-1])

# transpose of matrix_3x3_np
print("transpose of matrix_3x3_np:", matrix_3x3_np.T)

# rotate matrix_3x3_np by 90 degrees
print("rotate matrix_3x3_np by 90 degrees:", np.rot90(matrix_3x3_np))

# rotate matrix_3x3_np by -90 degrees
print("rotate matrix_3x3_np by -90 degrees:", np.rot90(matrix_3x3_np, -1))

# rotate matrix_3x3_np by 180 degrees
print("rotate matrix_3x3_np by 180 degrees:", np.rot90(matrix_3x3_np, 2))

3 x 3 matrix: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
3 x 3 matrix in numpy: [[1 2 3]
 [4 5 6]
 [7 8 9]]
last row of matrix_3x3_np: [7 8 9]
last element of last row of matrix_3x3_np: 9
transpose of matrix_3x3_np: [[1 4 7]
 [2 5 8]
 [3 6 9]]
rotate matrix_3x3_np by 90 degrees: [[3 6 9]
 [2 5 8]
 [1 4 7]]
rotate matrix_3x3_np by -90 degrees: [[7 4 1]
 [8 5 2]
 [9 6 3]]
rotate matrix_3x3_np by 180 degrees: [[9 8 7]
 [6 5 4]
 [3 2 1]]
identity matrix: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
# identity matrix
print("identity matrix:", np.eye(3))

identity matrix: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
idempotent operation: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
import tensorflow as tf

print("It's tensorflow! It has type {}".format(type(tf)))

a = tf.constant(2)
b = tf.constant(3)
print("a + b:", a + b)
c = tf.add(a, b)
print("c:", c)
print("c == a + b:", c == a + b)

It's tensorflow! It has type <class 'module'>
a + b: tf.Tensor(5, shape=(), dtype=int32)
c: tf.Tensor(5, shape=(), dtype=int32)
c == a + b: tf.Tensor(True, shape=(), dtype=bool)


In [11]:
def blackjack_hand_greater_than(hand_1, hand_2):
    """
    Return True if hand_1 beats hand_2, and False otherwise.
    
    In order for hand_1 to beat hand_2 the following must be true:
    - The total of hand_1 must not exceed 21
    - The total of hand_1 must exceed the total of hand_2 OR hand_2's total must exceed 21
    
    Hands are represented as a list of cards. Each card is represented by a string.
    
    When adding up a hand's total, cards with numbers count for that many points. Face
    cards ('J', 'Q', and 'K') are worth 10 points. 'A' can count for 1 or 11.
    
    When determining a hand's total, you should try to count aces in the way that 
    maximizes the hand's total without going over 21. e.g. the total of ['A', 'A', '9'] is 21,
    the total of ['A', 'A', '9', '3'] is 14.
    
    Examples:
    >>> blackjack_hand_greater_than(['K'], ['3', '4'])
    True
    >>> blackjack_hand_greater_than(['K'], ['10'])
    False
    >>> blackjack_hand_greater_than(['K', 'K', '2'], ['3'])
    False
    >>> blackjack_hand_greater_than(['J', 'A', 'A', '2'], ['9', '6', 'K', 'A', '5', 'J'])
    True
    """
    def total(hand):
        total = 0
        aces = 0
        for card in hand:
            if card in ['J', 'Q', 'K']:
                total += 10
            elif card == 'A':
                aces += 1
            else:
                total += int(card)
        total += aces
        while total + 10 <= 21 and aces > 0:
            total += 10
            aces -= 1
        return total
    
    return total(hand_1) <= 21 and (total(hand_1) > total(hand_2) or total(hand_2) > 21)

print(blackjack_hand_greater_than(['K'], ['3', '4']))
print(blackjack_hand_greater_than(['K'], ['10']))
print(blackjack_hand_greater_than(['K', 'K', '2'], ['3']))
print(blackjack_hand_greater_than(['J', 'A', 'A', '2'], ['9', '6', 'K', 'A', '5', 'J']))


True
False
False
True
